pipeline {
    agent any
    triggers { 
        pollSCM('H */4 * * 1-5') 
    }
    stages {
        stage('Git checkout') {
            steps {
                git branch: "main",
                    credentialsId: "BlueOcean Folder Credentials",
                    url: "https://github.com/duongphamtb/jenkins_test"
            }
        }
        stage('Build') {
            steps {
                echo 'build lan 4..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}