pipeline {
    agent any

    stages {
        // stage('Git checkout') {
        //     steps {
        //         git branch: "main",
        //             credentialsId: "jenkins-github-ssh-credentials",
        //             url: "git@github.com:duongphamtb/jenkins_test.git"
        //     }
        // }
        stage('Build') {
            steps {
                echo 'Buildingfdsfdsf..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}