pipeline {
    agent any

    stages {
        stage('Git checkout') {
            steps {
                git branch: "main",
                    credentialsId: "123456789",
                    url: "git@github.com:duongphamtb/jenkins_test.git"
            }
        }
        stage('Build') {
            steps {
                echo 'Building11111..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}