- name: Deploy the application secrets to the "staging" server
  hosts: staging
  #remote_user: root
  become: yes
  ##become: yes
  become_user: root
  roles:
    - role: ../roles/nginx
  tags:
    - bastion